# This is a basic workflow to help you get started with Actions

name: Bump version

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  status-checks:
    name: Bump version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        
      - name: Bump version
        run: npx lerna version --conventional-commits --yes
