# This is a basic workflow to help you get started with Actions

name: Bump version

on:
  workflow_dispatch:

jobs:
  status-checks:
    name: Bump version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Bump version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          pnpm lerna version --conventional-commits --yes
