# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  status-checks:
    name: Bump version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Bump version
        run: npx lerna version --conventional-commits
