name: Run checks

on:
  pull_request:
    branches:
      - main


jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.6
    with:
      fetch-depth: 0
      number-of-agents: 3
      init-commands: |
        yarn nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        yarn nx-cloud record -- yarn nx workspace-lint
      parallel-commands-on-agents: |
        yarn nx affected --target=lint --base=origin/main --head=HEAD --parallel=3
        yarn nx affected --target=test --base=origin/main --head=HEAD --parallel=3 --ci --code-coverage
        yarn nx affected --target=build --base=origin/main --head=HEAD --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.6
    with:
      number-of-agents: 3
