name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.6
    with:
      number-of-agents: 4
      init-commands: |
        yarn nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        yarn nx-cloud record -- yarn nx workspace-lint
      parallel-commands-on-agents: |
        yarn nx affected --target=lint --parallel=4
        yarn nx affected --target=test --parallel=4 --ci --code-coverage
        yarn nx affected --target=build --parallel=4
        yarn nx affected --target=visual --parallel=4

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.6
    with:
      number-of-agents: 4
