# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build affected
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build affected
        run: npx nx affected:build --base=origin/main --head=HEAD

  test:
    name: Test affected
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test affected
        run: npx nx affected:test --base=origin/main --head=HEAD

  build-component-lib:
    name: Build shared components
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build component library
        run: npx nx build @mordech/components

  visual-tests:
    needs: [build-component-lib]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: storybook
          path: storybook-static

      - name: visually test
        run: yarn workspace @mordech/components test:visual
