# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  status-checks:
    name: Build & test affected
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run checks
        run: |
          yarn nx affected:build --base=origin/main --head=HEAD
          yarn nx affected:test --base=origin/main --head=HEAD
          yarn nx affected:lint --base=origin/main --head=HEAD
      
      - shell: pwsh
        id: check_file_changed
        run: |
          $diff = git diff --name-only HEAD^ HEAD

          $SourceDiff = $diff | Where-Object { $_ -match '^docs/' -or $_ -match '.md$' }
          $HasDiff = $SourceDiff.Length -gt 0

          Write-Host "::set-output name=docs_changed::$HasDiff"

      - name: visually test
        if: steps.check_file_changed.outputs.docs_changed == 'True'
        run: |
          yarn nx build @mordech/components
          yarn nx visual @mordech/components --requireReference
